# Generated by Django 3.2.4 on 2023-04-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='year',
            field=models.PositiveIntegerField(default=int),
        ),
    ]
